# Site settings
title: Pol Monclús Segarra
email: pomo894@vidalibarraquer.net
description: "Aquest és el meu primer lloc fet amb Jekyll i GitHub Pages!"
baseurl: ""                 # IMPORTANT: deixa buit perquè és el repositori principal
url: "https://pomo894.github.io"  # URL del teu lloc


github_username: pomo894     # opcional

# Build settings
theme: minima
plugins:
  - jekyll-feed
